//! Calculation report (Markdown) for the drafting stage — phase G6 / stage 6.
//!
//! A plain-text, version-control-friendly summary of a project's engineering
//! results: the conductor and stringing parameters, a per-span sag/tension/
//! clearance table, and a per-structure wind/weight-span load table, plus the
//! governing worst-case figures. Markdown keeps it readable as-is and renderable
//! to PDF/HTML by any downstream tool, matching the open-format goal of stage 6.

use std::fmt::Write as _;

use crate::analysis::{analyze, Analysis};
use crate::Project;

/// Render a full Markdown calculation report for `project`.
pub fn markdown(project: &Project) -> String {
    let analysis = analyze(project);
    markdown_with(project, &analysis)
}

/// Render the report from a pre-computed [`Analysis`] (avoids re-solving when the
/// caller already has one, e.g. the GUI).
pub fn markdown_with(project: &Project, analysis: &Analysis) -> String {
    let mut s = String::new();
    let c = &project.conductor;
    let p = &project.parameters;

    let _ = writeln!(s, "# ATLDP calculation report — {}", project.metadata.name);
    let _ = writeln!(s);
    if !project.metadata.notes.is_empty() {
        let _ = writeln!(s, "{}", project.metadata.notes);
        let _ = writeln!(s);
    }
    let _ = writeln!(s, "_Generated by ATLDP {}._", crate::VERSION);
    let _ = writeln!(s);

    // ── inputs ──
    let _ = writeln!(s, "## Conductor & stringing");
    let _ = writeln!(s);
    let _ = writeln!(s, "| Property | Value |");
    let _ = writeln!(s, "| --- | --- |");
    let _ = writeln!(s, "| Conductor | {} |", c.name);
    let _ = writeln!(s, "| Unit weight | {:.3} N/m |", c.unit_weight_n_per_m);
    let _ = writeln!(s, "| Diameter | {:.1} mm |", c.diameter_m * 1000.0);
    let _ = writeln!(s, "| Rated strength | {:.0} N |", c.rated_strength_n);
    let _ = writeln!(
        s,
        "| Horizontal tension | {:.0} N |",
        p.horizontal_tension_n
    );
    let _ = writeln!(s, "| Min. ground clearance | {:.1} m |", p.min_clearance_m);
    let _ = writeln!(s, "| Wind pressure | {:.0} Pa |", p.wind_pressure_pa);
    let _ = writeln!(s);

    // ── spans ──
    let _ = writeln!(s, "## Spans");
    let _ = writeln!(s);
    if analysis.spans.is_empty() {
        let _ = writeln!(s, "_No spans (fewer than two towers spotted)._");
        let _ = writeln!(s);
    } else {
        let _ = writeln!(
            s,
            "| Span | Length (m) | Δh (m) | Sag (m) | Max tension (N) | % RTS | Min clear (m) | OK |"
        );
        let _ = writeln!(s, "| --- | ---: | ---: | ---: | ---: | ---: | ---: | :-: |");
        for sp in &analysis.spans {
            let clr = sp
                .min_clearance_m
                .map(|c| format!("{c:.1}"))
                .unwrap_or_else(|| "—".to_string());
            let ok = match sp.min_clearance_m {
                None => "—",
                Some(_) if sp.clearance_ok => "✓",
                Some(_) => "✗",
            };
            let _ = writeln!(
                s,
                "| S{}–{} | {:.0} | {:+.1} | {:.2} | {:.0} | {:.1} | {} | {} |",
                sp.from_tower + 1,
                sp.to_tower + 1,
                sp.horizontal_m,
                sp.elevation_diff_m,
                sp.sag_m,
                sp.max_tension_n,
                sp.tension_pct_rts,
                clr,
                ok,
            );
        }
        let _ = writeln!(s);
    }

    // ── structures ──
    let _ = writeln!(s, "## Structure loads");
    let _ = writeln!(s);
    if analysis.structures.is_empty() {
        let _ = writeln!(s, "_No structures._");
        let _ = writeln!(s);
    } else {
        let _ = writeln!(
            s,
            "| Tower | Wind span (m) | Weight span (m) | Transverse load (N) | Vertical load (N) |"
        );
        let _ = writeln!(s, "| --- | ---: | ---: | ---: | ---: |");
        for st in &analysis.structures {
            let l = &st.loads;
            let _ = writeln!(
                s,
                "| T{} | {:.0} | {:.0} | {:.0} | {:.0} |",
                st.tower + 1,
                l.wind_span_m,
                l.weight_span_m,
                l.transverse_load_n,
                l.vertical_load_n,
            );
        }
        let _ = writeln!(s);
    }

    // ── summary ──
    let _ = writeln!(s, "## Summary");
    let _ = writeln!(s);
    match analysis.worst_clearance_m {
        Some(c) => {
            let verdict = if analysis.all_clearances_ok() {
                "within the criterion"
            } else {
                "**below the criterion**"
            };
            let _ = writeln!(
                s,
                "- Worst ground clearance: **{c:.1} m** (limit {:.1} m) — {verdict}.",
                p.min_clearance_m
            );
        }
        None => {
            let _ = writeln!(s, "- Ground clearance: not evaluated (no terrain profile).");
        }
    }
    if let Some(t) = analysis.max_tension_pct_rts {
        let _ = writeln!(
            s,
            "- Peak tension utilisation: **{t:.1}%** of rated strength."
        );
    }
    let _ = writeln!(s, "- Towers: {}", project.towers.len());

    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ProfileSample, Tower};

    fn project() -> Project {
        let mut p = Project::new("Report test");
        p.ground_profile = vec![
            ProfileSample {
                distance_m: 0.0,
                elevation_m: 100.0,
            },
            ProfileSample {
                distance_m: 600.0,
                elevation_m: 100.0,
            },
        ];
        p.towers = vec![
            Tower {
                distance_m: 0.0,
                ground_elevation_m: 100.0,
                attachment_height_m: 20.0,
            },
            Tower {
                distance_m: 300.0,
                ground_elevation_m: 100.0,
                attachment_height_m: 20.0,
            },
            Tower {
                distance_m: 600.0,
                ground_elevation_m: 100.0,
                attachment_height_m: 20.0,
            },
        ];
        p
    }

    #[test]
    fn report_has_sections_and_rows() {
        let md = markdown(&project());
        assert!(md.contains("# ATLDP calculation report — Report test"));
        assert!(md.contains("## Spans"));
        assert!(md.contains("## Structure loads"));
        assert!(md.contains("## Summary"));
        assert!(md.contains("S1–2"));
        assert!(md.contains("T2"));
        assert!(md.contains("of rated strength"));
    }

    #[test]
    fn report_notes_missing_terrain() {
        let mut p = project();
        p.ground_profile.clear();
        let md = markdown(&p);
        assert!(md.contains("not evaluated (no terrain profile)"));
    }
}
