//! Calculation report (Markdown) for the drafting stage — phase G6 / stage 6.
//!
//! A plain-text, version-control-friendly summary of a project's engineering
//! results: the conductor and stringing parameters, a per-span sag/tension/
//! clearance table, and a per-structure wind/weight-span load table, plus the
//! governing worst-case figures. Markdown keeps it readable as-is and renderable
//! to PDF/HTML by any downstream tool, matching the open-format goal of stage 6.

use std::fmt::Write as _;

use crate::analysis::{analyze, Analysis};
use crate::Project;

/// Render a full Markdown calculation report for `project`.
pub fn markdown(project: &Project) -> String {
    let analysis = analyze(project);
    markdown_with(project, &analysis)
}

/// Render the report from a pre-computed [`Analysis`] (avoids re-solving when the
/// caller already has one, e.g. the GUI).
pub fn markdown_with(project: &Project, analysis: &Analysis) -> String {
    let mut s = String::new();
    let p = &project.parameters;
    let multi_wire = project.wires.len() > 1;

    let _ = writeln!(s, "# ATLDP calculation report — {}", project.metadata.name);
    let _ = writeln!(s);
    if !project.metadata.notes.is_empty() {
        let _ = writeln!(s, "{}", project.metadata.notes);
        let _ = writeln!(s);
    }
    let _ = writeln!(s, "_Generated by ATLDP {}._", crate::VERSION);
    let _ = writeln!(s);

    // ── wires ──
    let _ = writeln!(s, "## Wires");
    let _ = writeln!(s);
    if project.wires.is_empty() {
        let _ = writeln!(s, "_No wires defined._");
        let _ = writeln!(s);
    } else {
        let _ = writeln!(
            s,
            "| Wire | Role | Conductor | Unit wt (N/m) | Ø (mm) | RTS (N) | V-offset (m) | Tension (N) |"
        );
        let _ = writeln!(s, "| --- | --- | --- | ---: | ---: | ---: | ---: | ---: |");
        for w in &project.wires {
            let c = &w.conductor;
            let _ = writeln!(
                s,
                "| {} | {} | {} | {:.3} | {:.1} | {:.0} | {:+.1} | {:.0} |",
                w.name,
                match w.role {
                    crate::WireRole::Phase => "phase",
                    crate::WireRole::Shield => "shield",
                },
                c.name,
                c.unit_weight_n_per_m,
                c.diameter_m * 1000.0,
                c.rated_strength_n,
                w.vertical_offset_m,
                w.tension_n,
            );
        }
        let _ = writeln!(s);
    }
    let _ = writeln!(s, "Min. ground clearance: {:.1} m. ", p.min_clearance_m);
    let _ = writeln!(s, "Wind pressure: {:.0} Pa.", p.wind_pressure_pa);
    let _ = writeln!(s);

    // ── tension sections ──
    let _ = writeln!(s, "## Tension sections");
    let _ = writeln!(s);
    if analysis.sections.is_empty() {
        let _ = writeln!(s, "_No sections (fewer than two towers spotted)._");
        let _ = writeln!(s);
    } else {
        let _ = writeln!(s, "| Section | Towers | Spans | Ruling span (m) |");
        let _ = writeln!(s, "| --- | --- | ---: | ---: |");
        for sec in &analysis.sections {
            let _ = writeln!(
                s,
                "| {} | T{}–T{} | {} | {:.0} |",
                sec.index + 1,
                sec.from_tower + 1,
                sec.to_tower + 1,
                sec.span_count,
                sec.ruling_span_m,
            );
        }
        let _ = writeln!(s);
    }

    // ── spans ──
    let _ = writeln!(s, "## Spans");
    let _ = writeln!(s);
    if analysis.spans.is_empty() {
        let _ = writeln!(s, "_No spans (fewer than two towers spotted)._");
        let _ = writeln!(s);
    } else {
        let wire_col = if multi_wire { " Wire |" } else { "" };
        let wire_sep = if multi_wire { " --- |" } else { "" };
        let _ = writeln!(
            s,
            "| Span |{wire_col} Length (m) | Δh (m) | Sag (m) | Max tension (N) | % RTS | Min clear (m) | OK |"
        );
        let _ = writeln!(
            s,
            "| --- |{wire_sep} ---: | ---: | ---: | ---: | ---: | ---: | :-: |"
        );
        for sp in &analysis.spans {
            let clr = sp
                .min_clearance_m
                .map(|c| format!("{c:.1}"))
                .unwrap_or_else(|| "—".to_string());
            let ok = match sp.min_clearance_m {
                None => "—",
                Some(_) if sp.clearance_ok => "✓",
                Some(_) => "✗",
            };
            let wire_cell = if multi_wire {
                format!(" {} |", project.wires[sp.wire].name)
            } else {
                String::new()
            };
            let _ = writeln!(
                s,
                "| S{}–{} |{wire_cell} {:.0} | {:+.1} | {:.2} | {:.0} | {:.1} | {} | {} |",
                sp.from_tower + 1,
                sp.to_tower + 1,
                sp.horizontal_m,
                sp.elevation_diff_m,
                sp.sag_m,
                sp.max_tension_n,
                sp.tension_pct_rts,
                clr,
                ok,
            );
        }
        let _ = writeln!(s);
    }

    // ── structures ──
    let _ = writeln!(s, "## Structure loads");
    let _ = writeln!(s);
    if analysis.structures.is_empty() {
        let _ = writeln!(s, "_No structures._");
        let _ = writeln!(s);
    } else {
        let _ = writeln!(
            s,
            "| Tower | Function | Wind span (m) | Weight span (m) | Transverse load (N) | Vertical load (N) | Family | Chart |"
        );
        let _ = writeln!(s, "| --- | --- | ---: | ---: | ---: | ---: | --- | :-: |");
        for st in &analysis.structures {
            let family = st.family.as_deref().unwrap_or("—");
            let chart = match st.chart_ok {
                None => "—",
                Some(true) => "✓",
                Some(false) => "✗",
            };
            let _ = writeln!(
                s,
                "| T{} | {} | {:.0} | {:.0} | {:.0} | {:.0} | {} | {} |",
                st.tower + 1,
                st.function.label(),
                st.wind_span_m,
                st.weight_span_m,
                st.transverse_load_n,
                st.vertical_load_n,
                family,
                chart,
            );
        }
        let _ = writeln!(s);
    }

    // ── summary ──
    let _ = writeln!(s, "## Summary");
    let _ = writeln!(s);
    match analysis.worst_clearance_m {
        Some(c) => {
            let verdict = if analysis.all_clearances_ok() {
                "within the criterion"
            } else {
                "**below the criterion**"
            };
            let _ = writeln!(
                s,
                "- Worst ground clearance: **{c:.1} m** (limit {:.1} m) — {verdict}.",
                p.min_clearance_m
            );
        }
        None => {
            let _ = writeln!(s, "- Ground clearance: not evaluated (no terrain profile).");
        }
    }
    if let Some(t) = analysis.max_tension_pct_rts {
        let _ = writeln!(
            s,
            "- Peak tension utilisation: **{t:.1}%** of rated strength."
        );
    }
    if analysis.structures.iter().any(|s| s.chart_ok.is_some()) {
        let verdict = if analysis.all_charts_ok() {
            "all within their application charts"
        } else {
            "**one or more structures exceed their application chart**"
        };
        let _ = writeln!(s, "- Structure loading: {verdict}.");
    }
    let _ = writeln!(s, "- Wires: {}", project.wires.len());
    let _ = writeln!(s, "- Tension sections: {}", analysis.sections.len());
    let _ = writeln!(s, "- Towers: {}", project.towers.len());

    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ProfileSample, Tower};

    fn project() -> Project {
        let mut p = Project::new("Report test");
        p.ground_profile = vec![
            ProfileSample {
                distance_m: 0.0,
                elevation_m: 100.0,
            },
            ProfileSample {
                distance_m: 600.0,
                elevation_m: 100.0,
            },
        ];
        p.towers = vec![
            Tower {
                distance_m: 0.0,
                ground_elevation_m: 100.0,
                attachment_height_m: 20.0,
                ..Default::default()
            },
            Tower {
                distance_m: 300.0,
                ground_elevation_m: 100.0,
                attachment_height_m: 20.0,
                ..Default::default()
            },
            Tower {
                distance_m: 600.0,
                ground_elevation_m: 100.0,
                attachment_height_m: 20.0,
                ..Default::default()
            },
        ];
        p
    }

    #[test]
    fn report_has_sections_and_rows() {
        let md = markdown(&project());
        assert!(md.contains("# ATLDP calculation report — Report test"));
        assert!(md.contains("## Spans"));
        assert!(md.contains("## Structure loads"));
        assert!(md.contains("## Summary"));
        assert!(md.contains("S1–2"));
        assert!(md.contains("T2"));
        assert!(md.contains("of rated strength"));
    }

    #[test]
    fn report_notes_missing_terrain() {
        let mut p = project();
        p.ground_profile.clear();
        let md = markdown(&p);
        assert!(md.contains("not evaluated (no terrain profile)"));
    }
}
