//! Cross-implementation agreement: Rust `atldp-core` vs. the Python oracle over a
//! parameter sweep (ADR-0014 gate 2).
//!
//! The CSV fixtures in `tests/fixtures/` are the frozen output of the validated
//! Python `core/` (since retired, ADR-0014), generated by its
//! `validation/export_reference.py`. The fixtures are committed and are the
//! permanent record of that gate: this test recomputes each row in Rust and
//! asserts agreement within an explicit relative tolerance; a regression here
//! fails the build (ADR-0008).
//!
//! Tolerances are loose relative to the agreement actually observed: the catenary
//! closed forms are byte-for-byte the same maths on both sides (~1e-12); the
//! parabola arc length is the only systematic difference — exact closed form here
//! vs. `scipy.quad` in the oracle — and that agrees to ~1e-9. Change-of-state
//! tensions agree to ~1e-9 (bisection vs. `brentq`, both far inside their
//! brackets).

use std::fs;
use std::path::Path;

use atldp_core::catenary::{solve_span, Method};
use atldp_core::change_of_state::{change_of_state, StateCase};
use atldp_core::conductor::drake_acsr;

/// Relative tolerance for the sweep. Comfortably above the observed agreement
/// (~1e-9) yet tight enough that any real divergence is caught.
const REL_TOL: f64 = 1e-7;

fn rel_close(rust: f64, py: f64) -> bool {
    (rust - py).abs() <= REL_TOL * rust.abs().max(py.abs()).max(1.0)
}

fn read_fixture(name: &str) -> Vec<std::collections::HashMap<String, String>> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name);
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read fixture {}: {e}", path.display()));
    let mut lines = text.lines();
    let header: Vec<String> = lines
        .next()
        .unwrap()
        .split(',')
        .map(str::to_string)
        .collect();
    lines
        .filter(|l| !l.is_empty())
        .map(|line| {
            header
                .iter()
                .cloned()
                .zip(line.split(',').map(str::to_string))
                .collect()
        })
        .collect()
}

fn get(row: &std::collections::HashMap<String, String>, key: &str) -> f64 {
    row[key]
        .parse()
        .unwrap_or_else(|_| panic!("bad float for {key}: {:?}", row.get(key)))
}

#[test]
fn spans_sweep_matches_oracle() {
    let rows = read_fixture("oracle_spans.csv");
    assert!(!rows.is_empty(), "empty span fixture");
    for row in &rows {
        let method = Method::parse(&row["method_in"]).unwrap();
        let sol = solve_span(
            get(row, "S"),
            get(row, "h"),
            get(row, "w"),
            get(row, "H"),
            method,
        )
        .unwrap();

        assert_eq!(
            sol.method.as_str(),
            row["method_used"],
            "method selection diverged: {row:?}"
        );
        for (field, value) in [
            ("length", sol.conductor_length),
            ("sag", sol.sag),
            ("sag_position", sol.sag_position),
            ("low_point_x", sol.low_point_x),
            ("tension_start", sol.tension_start),
            ("tension_end", sol.tension_end),
        ] {
            let py = get(row, field);
            assert!(
                rel_close(value, py),
                "{field}: rust={value} python={py} row={row:?}"
            );
        }
    }
}

#[test]
fn change_of_state_sweep_matches_oracle() {
    let drake = drake_acsr();
    let w = drake.unit_weight;
    let rows = read_fixture("oracle_cos.csv");
    assert!(!rows.is_empty(), "empty change-of-state fixture");
    for row in &rows {
        let method = Method::parse(&row["method_in"]).unwrap();
        let reference = StateCase::new("ref", get(row, "ref_temp"), w);
        let target = StateCase::new("tgt", get(row, "tgt_temp"), get(row, "tgt_w"));
        let sol = change_of_state(
            &drake,
            get(row, "S"),
            get(row, "h"),
            get(row, "ref_H"),
            &reference,
            &target,
            method,
        )
        .unwrap();

        for (field, value) in [
            ("H2", sol.h_tension),
            ("length", sol.conductor_length),
            ("sag", sol.sag),
            ("tension_start", sol.tension_start),
            ("tension_end", sol.tension_end),
        ] {
            let py = get(row, field);
            assert!(
                rel_close(value, py),
                "{field}: rust={value} python={py} row={row:?}"
            );
        }
    }
}
